# Generated by Django 4.1.1 on 2022-09-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(default='N/A', max_length=100, null=True)),
                ('city', models.CharField(default='N/A', max_length=35, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip', models.CharField(default='XXXXX', max_length=5, null=True)),
                ('phone', models.CharField(default='XXX-XXX-XXXX', max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
